src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use App\ToolKitBQP;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use JsonSerializable;
use Symfony\Component\Validator\Constraints as Assert;



#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event implements JsonSerializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[Assert\LessThan(propertyPath: "dateFinish", message: "La date de début d'événement doit être avant la date de fin de l'événement!")]
    #[Assert\GreaterThan(new DateTime('now'), message:"La date de l'événement ne peux être antérieur à la date du jour !")]
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateStart = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateFinish = null;

    #[Assert\LessThan(propertyPath: "dateStart", message: "La date limite d'inscription doit être avant la date de début de l'événement!")]
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateLimit = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[Assert\GreaterThanOrEqual(1, message: "Le nombre de participant ne peux être inférieur à une personne !")]
    #[ORM\Column(nullable: true)]
    private ?int $peopleMax = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $cancelReason = null;

    #[ORM\ManyToOne(inversedBy: 'organizedEvents')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $organizer = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Location $location = null;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'events')]
    private Collection $users;

    #[ORM\Column(nullable: false)]
    private ?bool $isPublished = false;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->dateStart;
    }

    public function setDateStart(\DateTimeInterface $dateStart): self
    {
        $this->dateStart = $dateStart;

        return $this;
    }

    public function getDateFinish(): ?\DateTimeInterface
    {
        return $this->dateFinish;
    }

    public function setDateFinish(\DateTimeInterface $dateFinish): self
    {
        $this->dateFinish = $dateFinish;

        return $this;
    }

    public function getDateLimit(): ?\DateTimeInterface
    {
        return $this->dateLimit;
    }

    public function setDateLimit(\DateTimeInterface $dateLimit): self
    {
        $this->dateLimit = $dateLimit;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPeopleMax(): ?int
    {
        return $this->peopleMax;
    }

    public function setPeopleMax(?int $peopleMax): self
    {
        $this->peopleMax = $peopleMax;

        return $this;
    }

    public function getCancelReason(): ?string
    {
        return $this->cancelReason;
    }

    public function setCancelReason(?string $cancelReason): self
    {
        $this->cancelReason = $cancelReason;

        return $this;
    }

    public function getOrganizer(): ?User
    {
        return $this->organizer;
    }

    public function setOrganizer(?User $organizer): self
    {
        $this->organizer = $organizer;
        //auto apply pour son event
        $this->addUser($organizer);
        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addEvent($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeEvent($this);
        }

        return $this;
    }

    private function getUsersAsArray(): array
    {
        $usersAsArray = [];
        foreach($this->users as $user){
            $usersAsArray[] = $user->getEmail();
        }
        return $usersAsArray;
    }

    /**
     * ajouter-retirer un utilisateur
     * @param $applyUser
     * @return $this|null
     */
    public function apply($applyUser): ?static
    {
        $alreadyin=false;
        foreach($this->users as $user){
            if ($applyUser->getId() == $user->getId()){
                $alreadyin = true;
            }
        }
        if ($alreadyin){
            $this->removeUser($applyUser);
        }else if ($this->peopleMax == null || $this->getRoom()>0){
            $this->addUser($applyUser);
        }else {
            return null;
        }
        return $this;
    }

    /**
     * transforme les infos d'un objet en texte json
     * @return mixed
     *
     */
    public function jsonSerialize(): mixed
    {
        $tool = new toolKitBQP();
        return $tool->turnToUTF8([
            'organizer' => $this->organizer->getEmail(),
            'school'=> $this->organizer->getSchool()->getName(),
            'locationID' => $this->location->getId(),
            'locationName' => $this->location->getName(),
            'name' => $this->name,
            'dateStart' => $this->dateStart->format('Y-m-d H:i:s'),
            'dateFinish' => $this->dateFinish->format('Y-m-d H:i:s'),
            'dateLimit' => $this->dateLimit->format('Y-m-d H:i:s'),
            'description' => $this->description,
            'peopleMax' =>$this->peopleMax,
            'users'=> $this->getUsersAsArray()
        ]);
    }

    /**
     * @return int|null Indique le nombre de places restantes. Null si aucune limite
     */
    public function getRoom(){
        if($this->peopleMax == null){
            return null;
        }
        return $this->peopleMax - $this->users->count();
    }

    /**
     * @return string etat actuel calculé à partir des dates et du booléen "ispublished"
     */
    public function getState(): string
    {
        $today=new DateTime('now');
        if($this->dateFinish < $today){
            return 'FINISHED';
        }else if($this->dateStart < $today){
            return 'STARTED';
        }else if($this->dateLimit < $today){
            return 'CLOSED';
        }else if($this->isPublished){
            return 'PUBLISHED';
        }else{
            return 'UNPUBLISHED';
        }

    }

    public function isPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setPublished(bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }

}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use App\Entity\Location;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom'
            ])            ->add('location',
                EntityType::class,
                [
                    "class" => Location::class,
                    "choice_label" => "name",
                    "required"=>false
                ]
            )
            ->add('description')
            ->add('peopleMax', NumberType::class, [
                'label' => 'Limite d\'invités (optionnelle)'
            ])
            ->add('dateStart', DateTimeType::class, ['widget' => 'single_text',
                'label' => 'Début de l\'evenement'])
            ->add('dateFinish', DateTimeType::class, ['widget' => 'single_text',
                'label' => 'Fin de l\'evenement'])
            ->add('dateLimit', DateTimeType::class, ['widget' => 'single_text',
                'label' => 'Limite des inscriptions'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Form\EventDeleteType;
use App\Form\EventType;
use App\Form\QueryType;
use App\Memory;
use App\Repository\EventRepository;
use App\Repository\UserRepository;
use App\ToolKitBQP;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/event', name: 'event')]
class EventController extends AbstractController
{
    /*
     * voir toutes les sorties
     * avec filtre par queryForm
     */
    #[Route('/', name: '_index')]
    public function showAll(
        EntityManagerInterface $em,
        EventRepository        $evRepo,
        ToolKitBQP             $tool,
        Request                $request
    ): Response
    {
        //call archivage automatique à chaque accès au site
        $tool->autoArchive($em, $evRepo);
        //filtrage par la liste
        $research = $request->query->all('query');
        $keys = ['name', 'school', 'dateMin', 'dateMax'];
        $specifiedQuery = false;
        foreach ($keys as $key) {
            if (isset($research[$key])){
                $specifiedQuery = true;
            };
        }
        // TODO include organizer.id si boolean 'organizer'
        //obtenir les evenements tous ou par filtre
        if ($specifiedQuery) {
            $events = $evRepo->findByField($research);
        } else {
            $events = $evRepo->findAll();
        }
        //passer le formulaire type au twig
        $form = $this->createForm(QueryType::class);
        return $this->render('event/index.html.twig', [
            'form' => $form,
            'events' => $events
        ]);
    }

    /*
    * publier une sortie
    */
    #[IsGranted('ROLE_USER_VALID')]
    #[Route('/publish/{id}', name: '_publish', requirements: ['id' => '\d+'])]
    public function publish(
        int                    $id,
        EventRepository        $evRepo,
        EntityManagerInterface $em
    ): Response
    {
        //retrouver l'event en database
        $event = $evRepo->find($id);
        //si ni admin ni son propre event retour case départ
        if ($event == null || !$this->isGranted('ROLE_ADMIN') &&
            $this->getUser()->getUserIdentifier() !== $event->getOrganizer()->getEmail()) {
            return $this->redirectToRoute('home_index');
        }
        $event->setPublished(true);
        $em->persist($event);
        $em->flush();
        return $this->redirectToRoute('home_index');
    }


    /*
     * voir une sortie par id
     */
    #[IsGranted('ROLE_USER_VALID')]
    #[Route('/{id}', name: '_show', requirements: ['id' => '\d+'])]
    public function showOne(
        int             $id,
        EventRepository $evRepo
    ): Response
    {
        $event = $evRepo->findOneBy(['id' => $id]);
        return $this->render('event/unique.html.twig', [
            'event' => $event
        ]);
    }

    /*
     * Créer une sortie
     */
    #[IsGranted('ROLE_USER_VALID')]
    #[Route('/new', name: '_create')]
    public function create(
        UserRepository         $userRepo,
        EntityManagerInterface $em,
        Request                $request,
        Memory                 $mem
    ): Response
    {
        //trouver le mail loggué en session
        $mail = $this->getUser()->getUserIdentifier();
        $organizer = $userRepo->findOneBy(['email' => $mail]);
        //on récupere un new event() qui peux avoir des infos déjà renseignées
        $event = $mem->createAnEvent($mail);
        //on gère le formulaire normal de Event
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $event->setOrganizer($organizer);
            $em->persist($event);
            $em->flush();
            return $this->redirectToRoute('event_show', ["id" => $event->getId()]);
        }
        $this->addFlash('success', 'Votre evenement est bien enregistré');
        return $this->render('event/create.html.twig', [
                'form' => $form,
                'edit' => false
            ]
        );
    }

    /*
     * modifier une sortie par id
     */
    #[IsGranted('ROLE_USER_VALID')]
    #[Route('/edit/{id}', name: '_edit')]
    public function edit(
        int                    $id,
        EntityManagerInterface $em,
        Request                $request,
        EventRepository        $evRepo
    ): Response
    {

        //retrouver l'event en database
        $event = $evRepo->find($id);
        //si ni admin ni son propre event retour case départ
        if ($event == null || !$this->isGranted('ROLE_ADMIN') &&
            $this->getUser()->getUserIdentifier() !== $event->getOrganizer()->getEmail()) {
            return $this->redirectToRoute('home_index');
        }
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($event);
            $em->flush();
            return $this->redirectToRoute('event_show', ["id" => $event->getId()]);
        }
        $this->addFlash('success', 'Votre modification est bien enregistrée');
        return $this->render('event/create.html.twig', [
            'form' => $form,
            'edit' => true
        ]);
    }

    /*
     * supprimer un évenement
     */
    #[IsGranted('ROLE_USER_VALID')]
    #[Route('/remove/{id}', name: '_remove')]
    public function remove(
        int                    $id,
        EventRepository        $evRepo,
        EntityManagerInterface $em,
        Request                $request,
        ToolKitBQP             $tool
    ): Response
    {
        //retrouver l'event en database
        $event = $evRepo->find($id);
        //si ni admin ni son propre event retour case départ
        if (!$this->isGranted('ROLE_ADMIN') &&
            !$this->getUser()->getUserIdentifier() == $event->getOrganizer()->getEmail()) {
            $this->redirectToRoute('home_index');
        }
        //on fait remplir la raison de suppression
        $form = $this->createForm(EventDeleteType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            //ajout de la raison de suppression
            $event->setCancelReason($form->get('cancel_reason')->getData());

            //TODO envoyer un mail aux participants  function cancel($event)
            //archivage
            $tool->archive($event, $this->isGranted('ROLE_ADMIN') ? 'ADMIN' : 'USER', $em);

            return $this->redirectToRoute('event_index');
        }
        return $this->render('event/delete.html.twig', [
            'event' => $event,
            'delete_form' => $form,
            'edit' => true
        ]);
    }

    /*
     * ajouter un utilisateur à un event
     */
    #[IsGranted('ROLE_USER_VALID')]
    #[Route('/apply/{id}', name: '_apply')]
    public function apply(
        int                    $id,
        EventRepository        $evRepo,
        UserRepository         $userRepo,
        EntityManagerInterface $em
    ): Response
    {
        //retrouver l'event en database
        $event = $evRepo->find($id);
        $user = $userRepo->findOneBy(['email' => $this->getUser()->getUserIdentifier()]);
        //ajout/retrait de l'user dans l'event
        $event = $event->apply($user);
        $em->persist($event);
        $em->flush();
        $this->addFlash('success', 'Votre modification est bien enregistrée');

        return $this->redirectToRoute('home_index');
    }
}

templates/event/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ edit? 'Modifier':'Créer' }} un evenement - {{ parent() }}{% endblock %}

{% block body %}

    <div class="format">
        <div class="champForm">
            <h2>{{ edit? 'Modifier un ':'Creer un nouvel' }} Evènement</h2>
        </div>
        {{ form_start(form) }}
        <div class="champForm">
            {{ form_row(form.name) }}
        </div>
        <div class="champForm">
            {{ form_row(form.dateStart)}}
        </div>
        <div class="champForm">
            {{ form_row(form.dateFinish) }}
        </div>
        <div class="champForm">
            {{ form_row(form.peopleMax) }}
        </div>
        <div class="champForm">
            {{ form_row(form.description) }}
        </div>
        <div class="champForm">
            {{ form_row(form.location) }}
        </div>
        <div id="loc_create">(+)</div>

        <div class="champForm">
            {{ form_row(form.dateLimit) }}
        </div>
        <button class="glowing-btn glowing-txt to-left">{{ edit? 'Appliquer':'Créer' }}</button>
        {{ form_end(form) }}
        <br>
        <br>
        <br>
        <div><label for="school_name">Ecole de rattachement</label>
            <p id="school_name">{{ app.user.school.name }}</p></div>

        <a class="glowing-btn glowing-txt to-left" href="{{ path('home_index') }}">Retour à L'accueil</a>
    </div>

    <div id="hidden">{{ path('location_create') }}</div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('JS/addNewLocation.js') }}"></script>
{% endblock %}

templates/event/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ event.name }} - {{ parent() }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="center">
            <h2>Vous souhaitez annuler l'évènement: " {{ event.name }} "</h2>
            <p> Qui devait débuter le {{ event.dateStart.format('d/m/Y H:i') }}</p>
        </div>

        <div class="format">
            <div class="champForm">
                {{ form_start(delete_form) }}
            </div>

            <div class="champForm">
                {{ form_widget(delete_form) }}
            </div>

            <div class="center">
                <button class="button is-danger is-light">Archiver</button>
                {{ form_end(delete_form) }}
                <br>
                <a class="button is-link is-light" href="{{ path('home_index') }}">Retour à L'accueil</a>
            </div>

        </div>
    </div>

{% endblock %

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenements - {{ parent() }}{% endblock %}

{% block body %}


    <div class="container">
        <div class="form-container">
        <a class="glowing-btn glowing-txt to-left" href={{ path('event_create') }}>Nouvel Evènement</a><br>
            <br>
            <br>
        {{ form_start(form) }}
        {{ form_row(form.name) }}
        {{ form_row(form.dateMin) }}
        {{ form_row(form.dateMax) }}
        {{ form_row((form.school)) }}
        {{ form_row((form.organizer)) }}
        <button class="glowing-btn glowing-txt to-left">Filtrer</button>
        {{ form_end(form) }}
        </div>
        <br>
        <br>
        <br>
        <br>

        <div class="table-container">
        <table>
            <tr>
                <th>Quoi? (par qui?)</th>
                <th>Où ?</th>
                <th>De quand à quand ?</th>
                <th>Combien viennent?</th>
                <th>Etat</th>
                <th>Actions</th>
            </tr>

            {% set nbresult = 0 %}
            {% for event in events %}
                {% if (is_granted('ROLE_ADMIN') or event.organizer == app.user or event.published) %}
                    {% set nbresult = nbresult + 1 %}

                    <tr>
                        {# TODO Afficher une icone en fonction du type d'event #}
                        <td>
                            <p><a class="button is-primary is-outlined" href="{{ path('event_show', {'id': event.id}) }}">{{ event.name }}</a></p>
                            <p> par <a class="button is-primary is-outlined" href="{{ path('user_show', {'id': event.organizer.id}) }}">{{ event.organizer.pseudo }}</a></p>
                        </td>

                        <td><a class="button is-primary is-outlined" href="{{ path('location_show', {'id': event.location.id}) }}">{{ event.location.name }}</a>
                            <a class="button is-primary is-outlined" target="_blank"  href="https://www.google.fr/maps?q={{ event.location.latitude }},{{ event.location.longitude }}">Voir sur la carte</a>
                            {% if app.user %}
                            <p>A vol d'oiseau : {{ event.location.distanceFrom(app.user.school) }} Km</p>
                            {% endif %}
                        </td>

                        <td>
                            <p>{{ event.dateStart.format('d/m/Y H:i') }}</p> à <p>{{ event.dateFinish.format('d/m/Y H:i') }}</p>
                        </td>

                        <td>{% if event.room %}
                                {{ event.users.count }} / {{ event.peopleMax }} ( {{ event.room }} places dispo )
                            {% else %}
                                {{ event.users.count }} (Pas de limite)
                            {% endif %}
                        </td>

                        <td ><img class="{{ event.state }} state_img" src="../images/{{ event.state }}.png" alt="{{ event.state }}"></td>

                        <td>
                            {% if event.state != 'CLOSED' or is_granted('ROLE_ADMIN') %}
                                {% if (is_granted('ROLE_ADMIN') or event.organizer == app.user) %}
                                    <a class="button is-warning is-outlined" href={{ path('event_edit', {'id': event.id}) }}>Modifier</a>
                                    <a class="button is-danger is-outlined" href={{ path('event_remove',{'id':event.id}) }}>Supprimer</a>
                                {% endif %}
                                <a class="button is-primary is-outlined" href="{{ path('event_apply',{'id':event.id}) }}">{{ (app.user in event.users)? 'Ne plus participer':'Participer' }}</a>
                                {% if (event.state == 'UNPUBLISHED') %}
                                    <a class="button is-primary is-outlined" href="{{ path('event_publish',{'id':event.id}) }}">Publier</a>
                                {% endif %}
                            {% endif %}
                        </td>
                    </tr>

                {% endif %}
            {% endfor %}
        </table>
        </div>

        <H1 class="glow-green">Résultats : {{ nbresult }}</H1>
    </div>
{% endblock %}

templates/event/unique.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ event.name }} - {{ parent() }}{% endblock %}

{% block body %}
    <div class="container">
        <h2>Evènement {{ event.name }}</h2>
        <div>nom : {{ event.name }}</div>
        <br>
            <div><a class="button is-primary is-outlined" href="{{ path('location_show', {'id': event.location.id}) }}">{{ event.location.name }}</a>
                <a class="button is-primary is-outlined" target="_blank"  href="https://www.google.fr/maps?q={{ event.location.latitude }},{{ event.location.longitude }}">Voir sur la carte</a>
        </div>
        <br>

        <div>Début : {{ event.dateStart.format('d/m/Y H:i') }}</div>
        <div>Fin : {{ event.dateFinish.format('d/m/Y H:i') }}</div>
        <div>Clôture : {{ event.dateLimit.format('d/m/Y H:i') }}</div>

        <div>Etat : {{ event.state }}</div>
        <div>Organisateur : {{ event.organizer.pseudo }}</div>
        <div>A vol d'oiseau : {{ event.location.distanceFrom(app.user.school) }} Km</div>
        <br>
        <div>Participants</div>
        <div>{% if event.room %}
                {{ event.users.count }} / {{ event.peopleMax }} ( {{ event.room }} places dispo )
            {% else %}
                {{ event.users.count }} (Pas de limite)
            {% endif %}</div>
            <br>
        <div>{% for user in event.users %}
                <p><a class="button is-primary is-outlined" href="{{ path('user_show', {'id': user.id}) }}">{{ user.pseudo }}</a></p>
            {% endfor %}</div>

            <br>

    {% if event.state != 'CLOSED' or is_granted('ROLE_ADMIN') %}

            {% if (is_granted('ROLE_ADMIN') or event.organizer == app.user) %}
                <a class="button is-warning is-outlined" href={{ path('event_edit', {'id': event.id}) }}>Modifier</a>
                <a class="button is-danger is-outlined" href={{ path('event_remove',{'id':event.id}) }}>Supprimer</a>
            {% endif %}
            <a class="button is-primary is-outlined" href="{{ path('event_apply',{'id':event.id}) }}">{{ (app.user in event.users)? 'Ne plus participer':'Participer' }}</a>
            {% if (event.state == 'UNPUBLISHED') %}
                <a class="button is-primary is-outlined" href="{{ path('event_publish',{'id':event.id}) }}">Publier</a>
            {% endif %}

    {% endif %}
    <a class="button is-primary is-outlined" href="{{ path('home_index') }}">Retour à L'accueil</a>
    </div>
{% endblock %}